name: qclip_finetune_youtubeugc
seed: 42
load_path: ./pretrained_weights/qclip_lsvq_val-ltest_best.pth
num_epochs: 8
warmup_epochs: 1
save_model: false
output_dir: pretrained_weights
batch_size: 12
val_batch_size: 1
num_workers: 8

model:
  pe_config: PE-Core-L14-336
  checkpoint_path: ./pretrained_weights/PE-Core-L14-336.pt
  shared_dim: 128
  adapter_start_layer: 18
  num_context_tokens: 3

data:
  train:
    type: QCLIPVideoDataset
    args:
      phase: train
      anno_file: ./data_labels/YouTubeUGC/labels.txt
      data_prefix: ${DATA_ROOT}/original_videos_h264
      split: {role: train, ratio: 0.8, seed: 42}
  val-youtubeugc:
    type: QCLIPVideoDataset
    args:
      phase: test
      anno_file: ./data_labels/YouTubeUGC/labels.txt
      data_prefix: ${DATA_ROOT}/original_videos_h264
      split: {role: val, ratio: 0.8, seed: 42}

optimizer:
  lr: 1.0e-3
  wd: 1.0e-4
